services:
  docker-mysql:
    image: phanxuanloc2612/wing_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=26122002loc
      - MYSQL_DATABASE=wing
    ports:
      - 3307:3306
    volumes:
      - "../db:/var/lib/mysql"

  app:
    build: .
    ports:
      - 2612:8080
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/wing?autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql
